import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join, resolve } from "path";

const QuickWinSchema = z.object({
  action: z.string().describe("What to do"),
  where: z.string().describe("File, page, or location"),
  why: z.string().describe("Official reason or observed pattern"),
});

const FindingsSchema = z.object({
  url: z.string().url().describe("The URL that was analyzed"),
  diagnosis: z.string().describe("2-4 sentence summary of the core issue or opportunity"),
  quickWins: z.array(QuickWinSchema).describe("High-impact, low-effort actions for this week"),
  mediumTerm: z.array(z.string()).describe("Content or structural improvements for the next 4 weeks"),
  strategic: z.array(z.string()).describe("Bigger investments for 1-3 months out"),
  oneThingFirst: z.string().describe("The single most important action to take immediately"),
  outputDir: z
    .string()
    .optional()
    .describe(
      "Directory to save the report (default: ./seo-reports/ relative to current working directory)"
    ),
});

export function registerSaveReportTool(server: McpServer) {
  server.registerTool(
    "seo_save_report",
    {
      title: "Save SEO Audit Report",
      description:
        "Saves a complete SEO/GEO audit as a markdown file to disk. " +
        "Creates a dated file in ./seo-reports/ (or a custom directory) " +
        "with the full diagnosis, quick wins as checkboxes, medium-term items, " +
        "and strategic moves. Universal — works without any external integrations.",
      inputSchema: FindingsSchema,
    },
    async ({
      url,
      diagnosis,
      quickWins,
      mediumTerm,
      strategic,
      oneThingFirst,
      outputDir,
    }) => {
      // ── Build file path ──────────────────────────────────────────────────
      const now = new Date();
      const dateStr = now.toISOString().split("T")[0]; // YYYY-MM-DD
      const timeStr = now.toTimeString().split(" ")[0].replace(/:/g, "-"); // HH-MM-SS

      const hostname = (() => {
        try {
          return new URL(url).hostname.replace(/^www\./, "");
        } catch {
          return "unknown-site";
        }
      })();

      const filename = `${hostname}-${dateStr}.md`;
      const dir = resolve(outputDir ?? "./seo-reports");

      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }

      const filepath = join(dir, filename);

      // ── Build markdown content ───────────────────────────────────────────
      const lines: string[] = [
        `# SEO/GEO Audit — ${hostname}`,
        ``,
        `**URL:** ${url}  `,
        `**Date:** ${dateStr} ${timeStr}  `,
        `**Agent:** BodegaOne SEO/GEO Agent`,
        ``,
        `---`,
        ``,
        `## Diagnosis`,
        ``,
        diagnosis,
        ``,
        `---`,
        ``,
        `## Quick Wins — Do This Week`,
        ``,
        ...quickWins.map(
          (w, i) =>
            `- [ ] **${i + 1}. ${w.action}**  \n` +
            `  📍 ${w.where}  \n` +
            `  💡 ${w.why}`
        ),
        ``,
        `---`,
        ``,
        `## Medium Term — Next 4 Weeks`,
        ``,
        ...mediumTerm.map((item) => `- [ ] ${item}`),
        ``,
        `---`,
        ``,
        `## Strategic Moves — 1–3 Months`,
        ``,
        ...strategic.map((item) => `- [ ] ${item}`),
        ``,
        `---`,
        ``,
        `## ⚡ One Thing to Do First`,
        ``,
        `> ${oneThingFirst}`,
        ``,
        `---`,
        ``,
        `*Generated by [BodegaOne Agents](https://github.com/BodegaoneAI/bodegaone-agents)*`,
      ];

      const content = lines.join("\n");

      // ── Write file ───────────────────────────────────────────────────────
      try {
        writeFileSync(filepath, content, "utf-8");
      } catch (err) {
        return {
          content: [
            {
              type: "text" as const,
              text: `Failed to write report: ${err instanceof Error ? err.message : String(err)}\nAttempted path: ${filepath}`,
            },
          ],
          isError: true,
        };
      }

      return {
        content: [
          {
            type: "text" as const,
            text: [
              `✅ Report saved to: ${filepath}`,
              ``,
              `Quick summary:`,
              `  • ${quickWins.length} quick win${quickWins.length !== 1 ? "s" : ""} (checkboxes)`,
              `  • ${mediumTerm.length} medium-term item${mediumTerm.length !== 1 ? "s" : ""}`,
              `  • ${strategic.length} strategic move${strategic.length !== 1 ? "s" : ""}`,
              ``,
              `Open the file in any markdown viewer, paste into Notion/Docs, or track in git.`,
            ].join("\n"),
          },
        ],
      };
    }
  );
}
